apiVersion: v1
kind: Secret
metadata:
  name: directus-cms-secrets
  namespace: default
data:
  SECRET: {{ .Values.DIRECTUS_SECRET | b64enc }}
  ADMIN_EMAIL: {{ .Values.DIRECTUS_ADMIN_EMAIL | b64enc }}
  ADMIN_PASSWORD: {{ .Values.DIRECTUS_ADMIN_PASSWORD | b64enc }}
  