apiVersion: v1
kind: Service
metadata:
  name: directus-cms-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8055
  selector:
    name: directus-cms-deployment
  type: ClusterIP
  sessionAffinity: None
