apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: directus-cms-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: 'true'
spec:
  tls:
    - hosts:
        - cms.kspr.dev
      secretName: directus-cms-tls
  rules:
    - host: cms.kspr.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: directus-cms-service
                port:
                  number: 80
