apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kspr-dev-mfs-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - mfs.kspr.dev
      secretName: kspr-dev-mfs-tls
  rules:
    - host: mfs.kspr.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kspr-dev-mfs-service
                port:
                  number: 80
