apiVersion: v1
kind: Service
metadata:
  name: kspr-dev-shell-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    name: kspr-dev-shell-deployment
  type: ClusterIP
  sessionAffinity: None
