apiVersion: apps/v1
kind: Deployment
metadata:
  name: kspr-dev-mfs-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    name: kspr-dev-mfs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kspr-dev-mfs-deployment
  template:
    metadata:
      labels:
        name: kspr-dev-mfs-deployment
    spec:
      containers:
        - name: kspr-dev-mfs-deployment
          image: {{ .Values.MFS_IMAGE }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP