apiVersion: v1
kind: Service
metadata:
  name: kspr-dev-mfs-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: kspr-dev-mfs-deployment
  type: ClusterIP
  sessionAffinity: None
