FROM node:alpine as build

WORKDIR /app

COPY . /app/

RUN npm ci

RUN npm run build:prod

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]