apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kspr-pl-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - kspr.pl
      secretName: kspr-pl-tls
  rules:
    - host: kspr.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kspr-pl-service
                port:
                  number: 80
