kind: Ingress  
apiVersion: networking.k8s.io/v1
metadata:
  name: "kspr-dev-shell"
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  rules:
  - host: kspr.dev
    http:
      paths:
      - backend:
          service:
            name: kspr-dev-shell
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: kspr.dev
    http:
      paths:
      - backend:
          service:
            name: cdn-kspr
            port:
              number: 80
        path: /use-sse
        pathType: Prefix
    tls:
    - hosts:
      - kspr.dev
      secretName: kspr-dev-new-tls
                  