helm install \
--set DIRECTUS_CORS_ENABLED=$DIRECTUS_CORS_ENABLED \
--set DIRECTUS_CORS_ORIGIN=$DIRECTUS_CORS_ORIGIN \
--set DIRECTUS_DB_CLIENT=$DIRECTUS_DB_CLIENT \
--set DIRECTUS_DB_FILENAME=$DIRECTUS_DB_FILENAME \
--set DIRECTUS_WEBSOCKETS_ENABLED=$DIRECTUS_WEBSOCKETS_ENABLED \
--set DIRECTUS_SECRET=$DIRECTUS_SECRET \
--set DIRECTUS_ADMIN_EMAIL=$DIRECTUS_ADMIN_EMAIL \
--set DIRECTUS_ADMIN_PASSWORD=$DIRECTUS_ADMIN_PASSWORD \
kspr-dev ./kspr-dev