apiVersion: v1
kind: Service
metadata:
  name: cdn-kspr-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: cdn-kspr-dev-deployment
  type: ClusterIP
  sessionAffinity: None
