name: DeployCDN

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: environment
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
      
      - name: Load kube config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: mkdir -p ~/.kube/; echo "$KUBE_CONFIG" >> ~/.kube/config; chmod 600 ~/.kube/config
          
      - name: 'Deploy'
        run: |
          helm upgrade kspr-dev-cdn ./helm/kspr-dev-cdn \
            --install \
            --namespace ${{ vars.K8S_NAMESPACE }} \
            --create-namespace