name: Deploy

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build:prod
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kmoskwiak
          password: ${{ secrets.GHCR_KEY }}
      - name: List files
        run: ls -lah
      - name: Build and push mfs
        id: docker_build_mfs
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile.mfs
          tags: ghcr.io/kmoskwiak/kspr.dev-mfs:latest
      - name: Build and push shell
        id: docker_build_shell
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile.shell
          tags: ghcr.io/kmoskwiak/kspr.dev-shell:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
        id: install
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'kspr-dev'
          namespace: 'default'
          chart: './helm/kspr-dev'
          token: '${{ secrets.GHCR_KEY }}'
          values: |
            DIRECTUS_CORS_ENABLED: ${{ vars.DIRECTUS_CORS_ENABLED }}
            DIRECTUS_CORS_ORIGIN: ${{ vars.DIRECTUS_CORS_ORIGIN }}
            DIRECTUS_DB_CLIENT: ${{ vars.DIRECTUS_DB_CLIENT }}
            DIRECTUS_DB_FILENAME: ${{ vars.DIRECTUS_DB_FILENAME }}
            DIRECTUS_WEBSOCKETS_ENABLED: ${{ vars.DIRECTUS_WEBSOCKETS_ENABLED }}
            DIRECTUS_SECRET: ${{ secrets.DIRECTUS_SECRET }}
            DIRECTUS_ADMIN_EMAIL: ${{ secrets.DIRECTUS_ADMIN_EMAIL }}
            DIRECTUS_ADMIN_PASSWORD: ${{ secrets.DIRECTUS_ADMIN_PASSWORD }}
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'
      
     