name: DeployCMS

on:
  repository_dispatch:
    types: [dispatcher-trigger-digital-cicd]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production-cms'
        type: environment
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
      
      - name: Load kube config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: mkdir -p ~/.kube/; echo "$KUBE_CONFIG" >> ~/.kube/config; chmod 600 ~/.kube/config
          
      - name: 'Deploy'
        run: |
          helm upgrade kspr-dev-cms ./helm/kspr-dev-cms \
            --install \
            --set DIRECTUS_CORS_ENABLED="${{ vars.DIRECTUS_CORS_ENABLED }}" \
            --set DIRECTUS_CORS_ORIGIN="${{ vars.DIRECTUS_CORS_ORIGIN }}" \
            --set DIRECTUS_DB_CLIENT="${{ vars.DIRECTUS_DB_CLIENT }}" \
            --set DIRECTUS_DB_FILENAME="${{ vars.DIRECTUS_DB_FILENAME }}" \
            --set DIRECTUS_WEBSOCKETS_ENABLED="${{ vars.DIRECTUS_WEBSOCKETS_ENABLED }}" \
            --set DIRECTUS_SECRET="${{ secrets.DIRECTUS_SECRET }}" \
            --set DIRECTUS_ADMIN_EMAIL="${{ secrets.DIRECTUS_SECRET }}" \
            --set DIRECTUS_ADMIN_PASSWORD="${{ secrets.DIRECTUS_ADMIN_PASSWORD }}" \
            --namespace ${{ vars.K8S_NAMESPACE }} \
            --create-namespace