name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: environment
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build:prod
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kmoskwiak
          password: ${{ secrets.GHCR_KEY }}
      - name: List files
        run: ls -lah
      - name: Build and push mfs
        id: docker_build_mfs
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile.mfs
          tags: ghcr.io/kmoskwiak/kspr.dev-mfs:${{ github.sha }},ghcr.io/kmoskwiak/kspr.dev-mfs:latest
      - name: Build and push shell
        id: docker_build_shell
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile.shell
          tags: ghcr.io/kmoskwiak/kspr.dev-shell:${{ github.sha }},ghcr.io/kmoskwiak/kspr.dev-shell:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
      
      - name: Load kube config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: mkdir -p ~/.kube/; echo "$KUBE_CONFIG" >> ~/.kube/config; chmod 600 ~/.kube/config
          
      - name: 'Deploy'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'
        run: |
          helm upgrade kspr-dev ./helm/kspr-dev \
            --install \
            --set SHELL_IMAGE="ghcr.io/kmoskwiak/kspr.dev-shell:${{ github.sha }}" \
            --set MFS_IMAGE="ghcr.io/kmoskwiak/kspr.dev-mfs:${{ github.sha }}" \
            --namespace ${{ vars.K8S_NAMESPACE }} \
            --create-namespace
            
      
     